name: "build"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [python27, python36, python37, python38]
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: datakurre
    - run: make clean nix-show nix-docs PYTHON=${{ matrix.python }}
